<?php namespace ProcessWire;

class ImageFileDependencies extends WireData implements Module {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Image & File Dependencies',
			'version' => '0.0.4',
			'summary' => 'Allows Image and File fields to be used in inputfield dependency selectors. Note: prefix field names with an underscore in your dependency selectors.',
			'author' => 'Robin Sallis',
			'href' => 'https://github.com/Toutouwai/ImageFileDependencies',
			'icon' => 'question-circle',
			'autoload' => "template=admin",
			'requires' => 'ProcessWire>=3.0.0, PHP>=5.4.0',
		);
	}

	/**
	 * Ready
	 */
	public function ready() {
		// Hooks
		$this->addHookAfter('ProcessPageEdit::execute', $this, 'addScriptStyles');
		$this->addHookAfter('ProcessPageEdit::buildFormContent', $this, 'appendToForm');
	}

	/**
	 * Add script and styles
	 */
	public function addScriptStyles(HookEvent $event) {
		// Return if ProcessPageEdit is being loaded via AJAX (image field)
		if($this->wire()->config->ajax) return;

		// Add js for updating count fields
		$config = $this->wire()->config;
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config->scripts->add($config->urls->{$this->className} . "{$this->className}.js?v={$version}");

		// Add css for hiding count fields
		$event->return .= "<style>li.{$this->className} { display:none !important; }</style>";
	}

	/**
	 * Append fields to form
	 */
	public function appendToForm($event) {
		$page = $event->object->getPage();
		$form = $event->return;
		// Get Image and File fields in this form
		$flds = $form->find("class=FieldtypeImage|FieldtypeFile");
		// Create and append new fields for storing the image/file count
		foreach($flds as $fld) {
			$name = $fld->name;
			$count = $page->$name->count();
			$f = $this->wire()->modules->get('InputfieldText');
			$f->name = "_$name";
			$f->addClass($this->className, 'wrapClass');
			$f->value = $count;
			$form->append($f);
		}
	}

}
